redis:
  image: redis:5.0.4-stretch
  container_name: cache
  expose:
    - 6379

app:
  build: ./
  restart: always
  depends_on:
    - redis
  volumes:
    - ./:/app
  ports:
    - 3000:3000
  links:
    - redis
  environment:
    - REDIS_URL=redis://cache
    - NODE_ENV=development
  command:
    sh -c 'yarn install && yarn build && yarn serve'
